### ISSUE TITLE
timeout exeptions

### ISSUE THREAD

**Issue by StefanKDS** [anotherlab/UsbSerialForAndroid#15]
Hi,
if I Plugin the USB device directly everything works fine.
But if I put an USB Hub between, I get timeout expetions during Connection, Open,....
If I start Debugging, no Problem appears because of the short delay of each step.
Any idea ?

**Comment by anotherlab** [comment]
Hi @StefanKDS ,

This isn't really a problem with the library since it is working without the USB hub.  While low-speed hubs can introduce [latency issues](https://superuser.com/a/918245/194079), it shouldn't be enough to cause a problem.   We use this library on devices with external hubs and have not had any connection issues.  I would try a different hub.
