### ISSUE TITLE
Move from LGPL to MIT license

### ISSUE THREAD

**Issue by pravincar** [anotherlab/UsbSerialForAndroid#19]
HI @anotherlab, 

I've found your work to be pretty useful and see the potential for this library to be used more widely while getting more involvement from the open source community.

Would you consider moving the License for this library from LGPL to MIT considering that the source that this project is based on also changed the license?
https://github.com/mik3y/usb-serial-for-android/commit/2d13b90f59eec45adadaeed1aa593fe9a0d7540b

**Comment by anotherlab** [comment]
@pravincar I can't change the license because my port of @mik3y's FTDI driver is based on the LGPL code. He changed the license to MIT after rewriting the FTDI code to no longer use any LGPL code. If you would like to port his current implementation of the [FTDI driver](https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/FtdiSerialDriver.java) and submit a PR, I'll change the license to MIT.

**Comment by anotherlab** [comment]
And the FTDI driver has been rewritten to no longer have any LGPL dependencies. I based the changes on the work that @mik3y did, but I do not have the FTDI hardware to test the changes. 

The license has been moved to MIT.

**Comment by pravincar** [comment]
Thank you @anotherlab for the quick response!
