### ISSUE TITLE
Dotnet6 MAUI support

### ISSUE THREAD

**Issue by dannyhaak** [anotherlab/UsbSerialForAndroid#31]
It would be great to have a version that supports Dotnet6 with MAUI. I could get it to work with a new project file:

```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net6.0-android</TargetFrameworks>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<ReleaseVersion>0.0.0.1</ReleaseVersion>
	</PropertyGroup>
</Project>

```

A NuGet version would be even better. If you need any help, happy to make a PR to get this going.

**Comment by masterchen** [comment]
@dannyhaak  ,great job ! 
I also need MAUI  "version",  can you share me the way  how to port this lib to make  maui android  work ?

**Comment by aitchDashGee** [comment]
I think that creating a MAUI library in the proper sense probably is out of scope for this library, since it is focused on Android. Building for .NET 6 however is imho becoming a must, so I have created a [pull request for a multi targeted build of the library](https://github.com/anotherlab/UsbSerialForAndroid/pull/40), keeping backwards compatibility with monoandroid and introducing net6.0-android.

**Comment by dannyhaak** [comment]
Your solution sounds perfect. Looking forward to a release.

**Comment by anotherlab** [comment]
Thank you @aitchDashGee, I merged your PR this morning.
