### ISSUE TITLE
Ftdi throws error on Read method

### ISSUE THREAD

**Issue by patriciaOrtuno28** [anotherlab/UsbSerialForAndroid#39]
Hi, I have a program I have been using with the Cp21xx driver for a while. I decided to switch my hardware to an FTDI driver for stock reasons. The problem is that, with exactly the same software I had with Cp21xx, that worked, when switching to the FTDI it throws an error in the Read method (while the Write method seems to be working fine).
The error is the following (The Read method shows a -1 which in a BulkTransfer means failure):
```
[FtdiSerialDriver] Total bytes read=-1
[SerialInputOutputManager] Task ending due to exception: Expected at least 2 bytes
[UsbDeviceConnectionJNI] close
[SerialInputOutputManager] Task Ended!
```
As you can see in the Debug trace, the USB is correctly recognised:
```
[USB] USB device attached: /dev/bus/usb/001/002
```
The Write method also works fine:
```
[FtdiSerialDriver] claimInterface 0 SUCCESS
[SerialInputOutputManager] Task Started!
[FtdiSerialDriver] Wrote amtWritten=7 attempted=7
```
I'm sure there is a difference in how the Cp21xx and the Ftdi work internally and there must be a parameter that has to be modified. If somebody could guide me on what to change to have the Ftdi working as the Cp21xx did, I'd ve really thankful.

**Comment by anotherlab** [comment]
Without any additional feedback, we are closing this one

**Comment by TimDoesCode** [comment]
Hi @anotherlab 

I ran into this problem too when I switched from using an InputOutputManager to handle receiving data to using the raw port. When using the InputOutputManager everything worked as expected but if I directly run the same code on the UsbSerialPort, I run into the "Expected at least 2 bytes" exception.

The problem was the size of the buffer that was passed to the UsbSerialPort.Read() function. InputOutputManager was using a 4096 byte long buffer and mine was 10 byte long, because I was only expecting 10 bytes. I switched to a buffer that too is 4096 bytes long and then it worked.

`//does not work
byte[] buffer = new byte[10];
UsbSerialPort.Read(buffer, 1000);

//works
byte[] buffer = new byte[4096];
UsbSerialPort.Read(buffer, 1000);`
