### ISSUE TITLE
Unhandled exception with sequential read/ writes

### ISSUE THREAD

**Issue by sirin8** [anotherlab/UsbSerialForAndroid#7]
Thanks for your effort & sharing nice article about USB communication in Xamarin. I have tried your shared sample and managed to do read/write operations over USB channel. When I tried continuous sequential read, write operations after opening the channel I am getting exception "Unhandled exception" after the first try. 

This issue might be related to threads & tasks. I am new to C# & Xamarin, can you please help me out how can I resolve this if I have to work on sequential read, writes over USB channel. 

Greatly appreciate!!

**Comment by anotherlab** [comment]
I'm sorry, but this isn't the right place for a starter tutorial for C# or Xamarin.  Having said that, you should try to identify what line in your code is causing the exception.  If you think it's a threading issue, test a version of the code that does not use threading to see if you rule that as the root cause of the problem.
