### ISSUE TITLE
UsbManager DeviceList is Empty

### ISSUE THREAD

**Issue by CatimusPrime** [anotherlab/UsbSerialForAndroid#8]
Hello, 
  I am trying to use this library to connect my Xamarin.Forms (mainly Android) app to my PC via USB. When trying just the example, everything compiles correctly on my tablet (Acer Iconia 7 B1-780), however no devices are ever found when connected to my PC. I have tried using both regular and OTG cables, neither have given me any success. 

I have had success in connecting to an Arduino via the OTG cable, so I know the library works. Its just a matter of getting it to work with a PC connection that seems to escape me.  The laptop is a Dell Lattitute with an Intel USB controller chip, but don't know the vendor id or its product id. Is the problem just with the driver?

Any help on this would be greatly appreciated.
Cheers!

**Comment by anotherlab** [comment]
I think the problem is that your Android device and your PC are both acting as USB Hosts.  You can only have one USB host, which can talk to many devices.  This library is probably not the right tool for your task.  You may want to look at the [jMTP library](https://code.google.com/archive/p/jmtp/), as referenced in this [Stack Overflow thread](https://stackoverflow.com/questions/29513063/can-we-transfer-android-data-to-desktop-app-via-simple-usb-cable).

**Comment by EmilAlipiev** [comment]
@CatimusPrime what was your final solution? did you get something working?
